### ISSUE TITLE
Error with XICFinder

### ISSUE THREAD

**Issue by ngraham379** [PHOENIXcenter/deeprtalign#1]
I am trying to use XICFinder. I have my RAW files in a folder with XICFinder.exe and XICFinderMS1work.bat. I have installed MSFileReader.

When I double click XICFinderMS1work.bat, I receive the error:
"The system cannot find the path specified. 
work done!\(^o^)/~
Press any key to continue . . ."

Suggestions?

**Comment by changcheng1987** [comment]
Sorry for the late reply. Please move your files to a new directory and try again with XICFinder.exe. Before this, please install MSFilerReader for reading Thermo raw files.
[Uploading MSFileReader 3.0 SP3_x86_x64.zip…]()
